//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace K22CN3_TranDuyVu_Project02.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOAI_GAME
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LOAI_GAME()
        {
            this.GAMEs = new HashSet<GAME>();
        }
    
        public int ID { get; set; }
        public string MaLoaiGame { get; set; }
        public string TheLoaiGame { get; set; }
        public Nullable<byte> TrangThai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GAME> GAMEs { get; set; }
    }
}
